### =========================================
### PRISMA API
### =========================================

@basePrisma = http://localhost:3001
@userId = 1
@postId = 1
@commentId = 1

### Users - get all
GET {{basePrisma}}/users

### Users - create
POST {{basePrisma}}/users
Content-Type: application/json

{
  "name": "Ramiro Martínez",
  "email": "ramiro.martinez+demo@gmail.com"
}

### Users - get by id
GET {{basePrisma}}/users/{{userId}}

### Posts - create #1
POST {{basePrisma}}/posts
Content-Type: application/json

{
  "title": "Mis primer post usando la API de Prisma",
  "content": "Arrancando esta cuenta para compartir lo que voy aprendiendoo!",
  "authorId": 1
}

### Users - create with post
POST {{basePrisma}}/users/with-post
Content-Type: application/json

{
  "name": "Pedro Navarro",
  "email": "pedro.navarrodemo@acmeops.io",
  "post": {
    "title": "Mi primer post usando la API de Prisma",
    "content": "¡Probando cómo se siente crear contenido con Prisma ORM!"
  }
}

### Users - delete
DELETE {{basePrisma}}/users/1


### Posts - create #2
POST {{basePrisma}}/posts
Content-Type: application/json

{
  "title": "Qué es Prisma?",
  "content": "Es un ORM que nos permite interactuar con la base de datos de manera más sencilla y segura",
  "authorId": 2
}

### Posts - get with relations
GET {{basePrisma}}/posts/with-relations

### Posts - get by id
GET {{basePrisma}}/posts/{{postId}}

### Posts - delete (cascade comments)
DELETE {{basePrisma}}/posts/{{postId}}


### ---- Comments (por separado) ----

### Comments - create #1 (sobre post #1)
POST {{basePrisma}}/comments
Content-Type: application/json

{
  "content": "Felicitaciones, muy interesante tu post!",
  "postId": 1,
  "authorId": 2
}

### Comments - create #2 (sobre post #2)
POST {{basePrisma}}/comments
Content-Type: application/json

{
  "content": "Interesante!",
  "postId": 2,
  "authorId": 2
}

### =========================================
### DRIZZLE API
### =========================================

@baseDrizzle = http://localhost:3002
@dUserId = 1
@dPostId = 1
@dCommentId = 1

### Users - get all
GET {{baseDrizzle}}/users

### Users - get by id
GET {{baseDrizzle}}/users/{{dUserId}}

### Users - create
POST {{baseDrizzle}}/users
Content-Type: application/json

{
  "name": "Tomás Rojas",
  "email": "tomas.rojas+demo@acmeops.io"
}

### Users - create with post
POST {{baseDrizzle}}/users/with-post
Content-Type: application/json

{
  "name": "Diego Gomez",
  "email": "diego.gomez+demo@acmeops.io",
  "post": {
    "title": "Mi primer post usando la API de Drizzle",
    "content": "Probando crear una publicación con Drizzle ORM!"
  }
}

### Users - delete
DELETE {{baseDrizzle}}/users/{{dUserId}}


### ---- Posts (por separado) ----

### Posts - create #1
POST {{baseDrizzle}}/posts
Content-Type: application/json

{
  "title": "Primera vez usando Drizzle ORM",
  "content": "La forma en que Drizzle maneja las relaciones es muy interesante, permite mayor control que Prisma!",
  "authorId": 1
}

### Posts - create #2
POST {{baseDrizzle}}/posts
Content-Type: application/json

{
  "title": "Drizzle es una buena alternativa a Prisma",
  "content": "Si estas buscando un ORM cercano a SQL, Drizzle es una excelente opción para tus proyectos!",
  "authorId": 2
}



### Posts - get with relations (relational query)
GET {{baseDrizzle}}/posts/with-relations-rq

### Posts - get with relations (manual join)
GET {{baseDrizzle}}/posts/with-relations-join

### Posts - get by id
GET {{baseDrizzle}}/posts/{{dPostId}}

### ---- Comments (por separado) ----

### Comments - create #1 (sobre post #1)
POST {{baseDrizzle}}/comments
Content-Type: application/json

{
  "content": "Muy buen post, estoy aprendiendo mucho sobre Drizzle!",
  "postId": 1,
  "authorId": 2
}

### Comments - create #2 (sobre post #2)
POST {{baseDrizzle}}/comments
Content-Type: application/json

{
  "content": "Totalmente de acuerdo, Drizzle es una excelente opción para proyectos que requieren un ORM más cercano a SQL",
  "postId": 2,
  "authorId": 1
}

### Comments - create #1 (sobre post #1)
POST {{baseDrizzle}}/comments
Content-Type: application/json

{
  "content": "Felicitaciones, muy interesante tu post!",
  "postId": 1,
  "authorId": 2
}

### Comments - create #2 (sobre post #2)
POST {{baseDrizzle}}/comments
Content-Type: application/json

{
  "content": "Interesante!",
  "postId": 2,
  "authorId": 2
}